### ISSUE TITLE
Make monster Buttons

### ISSUE THREAD

**Issue by thecodewizard** [nickdhondt/dungeons-and-dragons#27]
In tab 2, make a section containing the following items:
- a button foreach monster in the table 'monsters'. The button should contain the name of the monster.
- a textbox where the user can fill in his multiplier
- a button which confirms the action.

The user should see his current EXP, the EXP that will be added and the predicted total of EXP.
This changes while adapting the values.
(See attached wireframe)
-> This might be changed

![untitled](https://cloud.githubusercontent.com/assets/10565728/7342502/9c114c78-ecb5-11e4-8555-bd1c3331b7a0.png)

**Comment by nickdhondt** [comment]
Multiplier range: 1 - 20
