### ISSUE TITLE
Display Basic Data - Section Tab 1

### ISSUE THREAD

**Issue by thecodewizard** [nickdhondt/dungeons-and-dragons#30]
In the first tab, all of the basic data is displayed.
Here, a simple grouping is present:
- The current values of Attack, Defence, Walking, Mana and Health is shown. The maximum reachable amount will be next to the current value between brackets.
- The current values of Skillpoints, D20 penalty, Level, EXP and EXP multiplier will be displayed.
- The current values of Arrows and Gold Coins.
- The current turn of the hero
- Any plain text messenges that the hero might have.

The user cannot edit this data, this is done by the administrator.

**Comment by thecodewizard** [comment]
OPEN QUESTIONS:
- In what way will the turn be displayed? In turns-until-your-turn or just an identifier (you're the 3rd) that changes color when it's that hero's turn.
- Must a user be able to solely substract Arrows and Gold coins? Is this doable?

**Comment by thecodewizard** [comment]
The Incoming array is in the following syntax:
Array(
"user_id"=>,
"username"=>
"basic_data"=>array(1=>(
     "name_data_1"=>,
     "value_data_1"=>), 2=> ...)
)

**Comment by thecodewizard** [comment]
All the data must be displayed, if not found in the array, the data is presumed 0.

**Comment by nickdhondt** [comment]
@thecodewizard we can display the turn by showing something like 2 turn to go and if it would be 0 turns to go the message changes to your turn (and changes color, etc.) So a parameter (using the stream) that indicates how many turns are left needs to be sent.

**Comment by thecodewizard** [comment]
the steam has been adapted to display that data. See the issue about "general array" for more information
