### ISSUE TITLE
If a user is registered what needs to happen?

### ISSUE THREAD

**Issue by nickdhondt** [nickdhondt/dungeons-and-dragons#31]
In which tables need to be inserted new records and what do these records contain. And if a user logs in, it needs to be detected that the user has no race and such. Which table needs to be checked to corfirm this and what needs to be inserted?

**Comment by nickdhondt** [comment]
@thecodewizard help requested. Only conceptual.

**Comment by thecodewizard** [comment]
owkay, if a user logs in, he must have a race and a class.
This means, if the value '0' is assigned for race or class, the 'choose race & class' window is prompted
