### ISSUE TITLE
Display maximum data in the basic tab - section 1

### ISSUE THREAD

**Issue by thecodewizard** [nickdhondt/dungeons-and-dragons#56]
In issue #55 , I will fetch the maximum values for the 5 first basic values. Should this be a valuable addition to the program if those 5 values are displayed next to the basic data.

That data could be added to the "basic" section of the array.
Note: this is only available for the first 5 basics. All the others don't have a basic value.

**Comment by nickdhondt** [comment]
@thecodewizard come si come si come ça? http://prntscr.com/6zn3z0

**Comment by nickdhondt** [comment]
@thecodewizard you could add an extra element in the basic_data array (you already have: name, value, etc.) called max.

**Comment by thecodewizard** [comment]
indeed, just like that.
I'll add those values to the "basic_data" array. This will be the best solution.
They will be called "max" and will be included in the same array as the basic_data "name", "value".
