### ISSUE TITLE
catch -1/+1 event on admin panel

### ISSUE THREAD

**Issue by thecodewizard** [nickdhondt/dungeons-and-dragons#64]
Make the server side events for the -1/+1 buttons in the admin panel.
Could @nickdhondt  provide me with the array structure? Thanks bruh

**Comment by nickdhondt** [comment]
@thecodewizard print_r(json_decode($_POST["data"]));

**Comment by nickdhondt** [comment]
In javascript this can't be done with an array, an object is created. Containing: basic_id, action, user_id
